services:
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
      - backend_venv:/app/.venv
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    ports:
      - "5432:5432"

volumes:
  backend_venv:
