"""add stream and stream key tables

Revision ID: 3f2126657b14
Revises: 560304374d8c
Create Date: 2026-06-11 20:05:00.283833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2126657b14'
down_revision: Union[str, Sequence[str], None] = '560304374d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('live', 'ended', name='stream_status'), server_default=sa.text("'live'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('playlist_path', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream'))
    )
    op.create_table('stream_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('key_type', sa.Enum('angler', 'tourney', name='stream_key_type'), server_default=sa.text("'angler'"), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='stream_key_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_key')),
    sa.UniqueConstraint('key', name=op.f('uq_stream_key_key'))
    )
    op.create_table('angler_stream',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('angler_id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['angler_id'], ['angler.id'], name=op.f('fk_angler_stream_angler_id_angler'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], name=op.f('fk_angler_stream_stream_id_stream'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_angler_stream')),
    sa.UniqueConstraint('angler_id', 'stream_id', name=op.f('uq_angler_stream_angler_id'))
    )
    op.create_table('angler_stream_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('angler_id', sa.Uuid(), nullable=False),
    sa.Column('stream_key_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['angler_id'], ['angler.id'], name=op.f('fk_angler_stream_key_angler_id_angler'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_key_id'], ['stream_key.id'], name=op.f('fk_angler_stream_key_stream_key_id_stream_key'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_angler_stream_key')),
    sa.UniqueConstraint('stream_key_id', name=op.f('uq_angler_stream_key_stream_key_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('angler_stream_key')
    op.drop_table('angler_stream')
    op.drop_table('stream_key')
    op.drop_table('stream')
    # drop_table does not drop the native PG enum types; without this a
    # downgrade -> upgrade cycle fails with "type already exists".
    sa.Enum(name='stream_status').drop(op.get_bind())
    sa.Enum(name='stream_key_status').drop(op.get_bind())
    sa.Enum(name='stream_key_type').drop(op.get_bind())
    # ### end Alembic commands ###
