"""add angler table

Revision ID: 560304374d8c
Revises: 
Create Date: 2026-06-04 02:48:45.818480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560304374d8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('angler',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'archived', name='angler_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('home_state', sa.String(length=2), nullable=True),
    sa.Column('home_town', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_angler')),
    sa.UniqueConstraint('slug', name=op.f('uq_angler_slug'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('angler')
    # drop_table does not drop the native enum type; do it explicitly so the
    # migration is reversible (a re-upgrade would otherwise find it present).
    sa.Enum(name='angler_status').drop(op.get_bind())
    # ### end Alembic commands ###
